name: CI Pipeline for EcommerceAPIv2

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Entorno para ejecutar'
        required: true
        default: 'main'

jobs:
  build-and-test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: .

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    - name: Restore projects
      run: |
        dotnet restore EcommerceAPI
        dotnet restore TestEcommerce

    - name: Build projects
      run: |
        dotnet build EcommerceAPI --configuration Release --no-restore
        dotnet build TestEcommerce --configuration Release --no-restore

    - name: Run Tests
      run: |
        dotnet test TestEcommerce

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestEcommerce/TestResults/*.trx
